version: "3"

services:
  artmux-server:
    container_name: artmux-server
    image: php:8.1-apache
    hostname: server
    restart: unless-stopped
    tty: true
    ports:   
      - ${PORT}:80
    volumes:
      - ./public:/var/www/html:ro