version: "3"

services:
  artmux-server:
    container_name: artmux-server
    image: artmux-server-prod
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    hostname: server
    restart: unless-stopped
    tty: true
    ports:   
      - ${PORT}:80